oc_web_agency_homepage:
    path:     /
    defaults: { _controller: OCWebAgencyBundle:Home:index }

# app/config/routing.yml


view_post_route:
    path:    /post
    defaults: {_controller: OCWebAgencyBundle:Post:viewPost }

create_post_route:
    path:    /post/create
    defaults: {_controller: OCWebAgencyBundle:Post:createPost }

update_post_route:
    path:    /post/update/{id}
    defaults: {_controller: OCWebAgencyBundle:Post:updatePost }

delete_post_route:
    path:    /post/delete/{id}
    defaults: {_controller: OCWebAgencyBundle:Post:deletePost }