fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin_user:
    resource: "@AdminUserBundle/Resources/config/routing.yml"
    prefix:   /

oc_web_agency:
    resource: "@OCWebAgencyBundle/Resources/config/routing.yml"
    prefix:   /